telegram_token: "5966365009:AAF6KidzrLcq_so-VsKiwiWpvIhsPk3txwA"

panels:
  - url: https://dehost.c4be51da7bfbc401bcbb9be126b8250a.online:2053
    username: admin
    password: н$Й<Т,01пиыШ
  
  - url: https://ushost.c4be51da7bfbc401bcbb9be126b8250a.online:2053
    username: admin
    password: н$Й<Т,01пиыШ
